services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '3307:3306'

    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/src:/etc/nginx/html
    ports:
      - '80:80'
    links:
      - db

  apache:
    build: ./apache-php
    restart: always
    volumes:
      - ./apache-php/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./apache-php/src:/var/www/html/
    ports:
      - '8082:80'

    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'

    healthcheck:
      test: ['CMD-SHELL', 'redis-cli ping | grep PONG']
      interval: 10s
      timeout: 5s
      retries: 3
